#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := BSE_APP_v3
# Compiler version
COMPILER_VERSION    := GNU ARM 4.7.3 (HWTetra)
#path compiler
PATH_COMPILER       :=E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/bin
# Configuration name
CFG_NAME        := GNU_ARM_RELEASE_TETRA
# Target file name (without extension)
TRG_FILE_NAME   := BSEAPPAPP0205

#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-islero-linux-gnueabi-gcc.exe
# Gnu Assembler executable
AS              := arm-islero-linux-gnueabi-as.exe
# Gnu Linker executable
LD              := arm-islero-linux-gnueabi-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-islero-linux-gnueabi-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-islero-linux-gnueabi-size.exe
# Gnu binary Obj Dump executable
OBJ_DUMP        := arm-islero-linux-gnueabi-objdump.exe
# Gnu binary strip executable
STRIP           := arm-islero-linux-gnueabi-strip.exe


#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-IInc \
-IIncGen \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/include/c++/4.7.3 \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/include/c++/4.7.3/arm-islero-linux-gnueabi \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/include/c++/4.7.3/backward \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3/include-fixed \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/include \
-isystemE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/sysroot/usr/include \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_EmvApi/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/PCL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Security \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TeliumPlusEmulation \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TPass \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp/ingenico \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/PCL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Security \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TeliumPlusEmulation \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TPass \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp/ingenico \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/inc \

#-------------------------------------------------------------------------------
# Includes path used in assembler process
#-------------------------------------------------------------------------------
INCLUDES_ASM_PATH   := \
-IInc \
-IIncGen \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_EmvApi/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/inc \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/OS \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/CommonTools \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Communication \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GOAL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/GTL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/PCL \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SDK \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/Security \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/SQLite \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TeliumPlusEmulation \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/c/Platform/TPass \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp \
-IC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/inc/cpp/ingenico \


#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
E:/Program\ Files/BSE_APP/2019/BSEAPP/BSE_APP_v3/FMG_TPlus.a \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libSecurityTp.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libbluetooth.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libwifi.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libpackip.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libTmsCall_TPlus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBGRAPHICS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/SPMCI_TPlus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/ExtraGPRS.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/TlvTree.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libwrapper_tplus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBTPLUSMANAGER.LIB \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBPROTOBUF.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBOS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/liblinklayer.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/SQLITELIB.a \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libSecurityTp.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libbluetooth.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libwifi.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libpackip.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libTmsCall_TPlus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/SPMCI_TPlus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/ExtraGPRS.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/TlvTree.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/libwrapper_tplus.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBTPLUSMANAGER.LIB \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBPROTOBUF.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBOS.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/liblinklayer.lib \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/SQLITELIB.a \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBSERVICE.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBSVCDIRPX.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBSVCDIRSK.T3L \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform/LIBGRAPHICS.T3L \
 \

#-------------------------------------------------------------------------------
# System libraries path to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS_PATH     := \
-LE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3 \
-LE:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/lib \
-LC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/lib \
-LC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/lib \
-LC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_EmvApi/HW_TETRA/gnu_473/lib \
-LC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform \
-LC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/OS \
-LC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform \
-LC:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/OS \
-LC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/lib \
-LC:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/lib \




#-------------------------------------------------------------------------------
# RPATH for libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS_RPATH_LINK   := \
-rpath-link=C:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_EmvApi/HW_TETRA/gnu_473/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/OS \
-rpath-link=E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3 \
-rpath-link=E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/OS \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib_for_dbg \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/Platform \
-rpath-link=C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/lib/OS \
-rpath-link=C:/Program\ Files/TeliumSDK/Easy\ Path\ to\ CLess\ 7.6.7.00/SDKTPLUS/HW_TETRA/gnu_473/lib \
-rpath-link=C:/Program\ Files/TeliumSDK/Easy\ Path\ to\ EMV\ 30.12.3.01/SDKTPLUS_Engine/HW_TETRA/gnu_473/lib \


#-------------------------------------------------------------------------------
# Package libraries to be included during link operation
#-------------------------------------------------------------------------------
PACKAGE_LIBS    :=\
-ldel \
-lDiscover \
-lDiscoverDPAS \
-leftpos \
-lexpresspay \
-linterac \
-lJCB \
-lpaypass \
-lpaywave \
-lqPBOC \
-lvisawave \
-lemvcochecksum \
-lemvengine \
-lemvapi \
-lSec \
-ltpass \
-lgtl \
-lGRAPHICLIB \
-lOSLAYER \
-lmifare \
-ltelinux \
-lquickpass \
-lSec \
-ltpass \
-lgtl \
-lOSLAYER \
-lmifare \
-ltelinux \
-lGRAPHICLIB \
-ldel \
-lDiscover \
-lDiscoverDPAS \
-leftpos \
-lexpresspay \
-linterac \
-lJCB \
-lpaypass \
-lpaywave \
-lqPBOC \
-lquickpass \
-lvisawave \
-lemvcochecksum \
-lemvengine \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYS_LIBS     :=\
-lgcov \
-lc \
-lgcc \
-lgcc_s \
-lstdc++ \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     :=\
	$(PACKAGE_LIBS)\
	$(SYS_LIBS)


#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN
BINARY_FILE_NO_STRIP     := $(OBJ_PATH)/$(TRG_FILE_NAME).T3A

#-------------------------------------------------------------------------------
# Result Listing files
#-------------------------------------------------------------------------------
# Binary file
LST_FILE     := $(OBJ_PATH)/$(TRG_FILE_NAME).lst

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# SIZE file location
INTER_SIZE_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).siz
#Includes opt file
INCLUDE_FILE_OPT:= $(OBJ_PATH)/includesFiles.opt
#Linker opt file
LD_OPT_FILE:=$(OBJ_PATH)/ldFile.opt

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall
# Default assembler options
AS_DEF_OPTS     := 
# Default linker options
LD_DEF_OPTS     := -z noexecstack --as-needed -I/lib/ld-linux.so.3 --exclude-libs ALL --sysroot=E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/sysroot -Map=$(INTER_MAP_FILE)
# Default linker options
OD_DEF_OPTS     := --disassemble --source --syms

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -mthumb -pg --coverage -fstack-protector-all  -D_ING_GNU_ARM_RELEASE_TETRA
CC_SPEC_OPTS    += 
CC_SPEC_OPTS    +=  -D__FRAMEWORK_TELIUM_PLUS__=1 -D_EXPORT_=1 -D_PACKAGE_NAME_=TeliumPlusSDK -DSDK_VERSION=111607 -D__TELIUM3__=1
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"BSEAPPAPP0205"' -DINGENICO_PIN -D_ING_TELIUM_SDK_LOC='"C:\Program Files\TeliumSDK\SDK11.16.7.PatchD"' -DICONMENU -D__TTQ__='"\xF7\xE0\xC0\x00"' -D_ING_TELIUM_SDK_NAME='"Telium SDK"' -D_ING_TELIUM_SDK_VERSION='"11.16.7.PatchD"' -D_ING_APPLI_FAMILY='"BSEAPPAPP"' -D_ING_APPLI_TYPE=0x6e -D_ING_APPLI_TELIUM_TETRA_FULL_BINARY_NAME='"BSEAPPAPP0205.T3A"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium Tetra"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_DATA_FILE_BINARY_NAME='"DATA006E"' -D_ING_APPLI_FULL_DATA_FILE_BINARY_NAME='"DATA006E.T3P"' -D_ING_APPLI_DATA_FILE_TELIUM_TETRA_BINARY_NAME='"DATA006E.T3P"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_NAME='"8001100205_BSEAPPAPP.P3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_TYPE='"A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_RANGE='"00"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_COUNTRY_CODE='"000"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_IDENTIFIER='"110"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_VERSION='"020500"' -D_ING_APPLI_TELIUM_TETRA_COMPONENT_NAME='"BSEAPPAPP0205.T3A"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_FAMILY='"BSEAPPAPP"' -D_ING_APPLI_TELIUM_TETRA_PACKAGE_ROOTNAME='"8001100205_BSEAPPAPP"' -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_RELEASE_TETRA"' -D_ING_APPLI_FULL_BINARY_NAME='"BSEAPPAPP0205.T3A"' -DDISABLE_PURE -DDISABLE_UNATTENDED -DDISABLE_INTERAC -DSSL_PROFILE_NAME='"TRATLSSSL"'
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_RELEASE_TETRA=1
AS_SPEC_OPTS    +=  --defsym __FRAMEWORK_TELIUM_PLUS__=1 --defsym _EXPORT_=1 --defsym _PACKAGE_NAME_=TeliumPlusSDK --defsym SDK_VERSION=111607 --defsym __TELIUM3__=1
AS_SPEC_OPTS    +=  $(INCLUDES_ASM_PATH)
# Specific linker options
LD_SPEC_OPTS    := 
# Specific strip options
ST_SPEC_OPTS    :=  --remove-section=.comment 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)
#ObjDump options
OD_OPTS         := $(OD_DEF_OPTS)
#Strip options
ST_OPTS         := $(ST_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/Entry.o \
$(OBJ_PATH)/AdviseMgr.o \
$(OBJ_PATH)/Backlight.o \
$(OBJ_PATH)/Buzzer.o \
$(OBJ_PATH)/ComEthernet.o \
$(OBJ_PATH)/ComGPRS.o \
$(OBJ_PATH)/ComModem.o \
$(OBJ_PATH)/ComPPP.o \
$(OBJ_PATH)/ComSerial.o \
$(OBJ_PATH)/ComUSB.o \
$(OBJ_PATH)/ConfFlash.o \
$(OBJ_PATH)/ConfHardware.o \
$(OBJ_PATH)/ConfSoftware.o \
$(OBJ_PATH)/crypto.o \
$(OBJ_PATH)/Delay.o \
$(OBJ_PATH)/DialogBox.o \
$(OBJ_PATH)/Display.o \
$(OBJ_PATH)/DLL.o \
$(OBJ_PATH)/dukpt.o \
$(OBJ_PATH)/EMV_ActionAnalysis.o \
$(OBJ_PATH)/EMV_AppSel.o \
$(OBJ_PATH)/EMV_CVM.o \
$(OBJ_PATH)/EMV_FinalSelect.o \
$(OBJ_PATH)/EMV_Init.o \
$(OBJ_PATH)/EMV_Manager.o \
$(OBJ_PATH)/EMV_OnlineProcessing.o \
$(OBJ_PATH)/EMV_ServicesEmv.o \
$(OBJ_PATH)/EMV_Stop.o \
$(OBJ_PATH)/EMV_Support.o \
$(OBJ_PATH)/EMV_UserInterface.o \
$(OBJ_PATH)/EMV_UserInterfaceDisplay.o \
$(OBJ_PATH)/English.o \
$(OBJ_PATH)/EPSTOOL_Convert.o \
$(OBJ_PATH)/EPSTOOL_PinEntry.o \
$(OBJ_PATH)/EPSTOOL_TlvTree.o \
$(OBJ_PATH)/EPSTOOL_Unicode.o \
$(OBJ_PATH)/FFMS.o \
$(OBJ_PATH)/FMG.o \
$(OBJ_PATH)/FontISO8859.o \
$(OBJ_PATH)/FontUTF8.o \
$(OBJ_PATH)/globals.o \
$(OBJ_PATH)/Goal.o \
$(OBJ_PATH)/Graphic.o \
$(OBJ_PATH)/IAC.o \
$(OBJ_PATH)/IAM.o \
$(OBJ_PATH)/iso8583.o \
$(OBJ_PATH)/Keyboard.o \
$(OBJ_PATH)/Layout.o \
$(OBJ_PATH)/LIB.o \
$(OBJ_PATH)/log.o \
$(OBJ_PATH)/Magnetic.o \
$(OBJ_PATH)/Mapapp.o \
$(OBJ_PATH)/MapTra.o \
$(OBJ_PATH)/MenuManager.o \
$(OBJ_PATH)/MenuProcessing.o \
$(OBJ_PATH)/Message.o \
$(OBJ_PATH)/OnlineProcessing.o \
$(OBJ_PATH)/Printer.o \
$(OBJ_PATH)/req.o \
$(OBJ_PATH)/rsp.o \
$(OBJ_PATH)/Schemes.o \
$(OBJ_PATH)/secureISO.o \
$(OBJ_PATH)/Smart.o \
$(OBJ_PATH)/Sqlite.o \
$(OBJ_PATH)/TaskAnimation.o \
$(OBJ_PATH)/TaskMutex.o \
$(OBJ_PATH)/TaskSemaphore.o \
$(OBJ_PATH)/Timer.o \
$(OBJ_PATH)/Utility.o \
$(OBJ_PATH)/VFS.o \
$(OBJ_PATH)/rev.o \
$(OBJ_PATH)/val.o \
$(OBJ_PATH)/TaskGPRS.o \
$(OBJ_PATH)/Cless_Batch.o \
$(OBJ_PATH)/Cless_BlackList.o \
$(OBJ_PATH)/Cless_Common.o \
$(OBJ_PATH)/Cless_Customisation.o \
$(OBJ_PATH)/Cless_DataExchange.o \
$(OBJ_PATH)/Cless_Discover.o \
$(OBJ_PATH)/Cless_DiscoverDPAS.o \
$(OBJ_PATH)/Cless_Disk.o \
$(OBJ_PATH)/Cless_DumpData.o \
$(OBJ_PATH)/Cless_ExplicitSelection.o \
$(OBJ_PATH)/Cless_ExpressPay.o \
$(OBJ_PATH)/Cless_Fill.o \
$(OBJ_PATH)/Cless_GlobalTransactionData.o \
$(OBJ_PATH)/Cless_Goal.o \
$(OBJ_PATH)/Cless_GuiState.o \
$(OBJ_PATH)/Cless_Interac.o \
$(OBJ_PATH)/Cless_Manager.o \
$(OBJ_PATH)/Cless_NameList.o \
$(OBJ_PATH)/Cless_Parameters.o \
$(OBJ_PATH)/Cless_PayPass.o \
$(OBJ_PATH)/Cless_payWave.o \
$(OBJ_PATH)/Cless_PinEnManagement.o \
$(OBJ_PATH)/Cless_PinEntryGoal.o \
$(OBJ_PATH)/Cless_PinManagement.o \
$(OBJ_PATH)/Cless_Receipt.o \
$(OBJ_PATH)/Cless_Scan.o \
$(OBJ_PATH)/Cless_Servcomm.o \
$(OBJ_PATH)/Cless_Settings.o \
$(OBJ_PATH)/Cless_Term.o \
$(OBJ_PATH)/Cless_Torn.o \
$(OBJ_PATH)/Cless_TransactionFile.o \
$(OBJ_PATH)/Cless_VisaWave.o \
$(OBJ_PATH)/Cless_XML.o \
$(OBJ_PATH)/perf_log.o \
$(OBJ_PATH)/UserInterfaceHelpers.o \
$(OBJ_PATH)/CLESS_lang.o \
$(OBJ_PATH)/fnc.o \
$(OBJ_PATH)/Cless_QuickPass.o \
$(OBJ_PATH)/ComSSL.o \
$(OBJ_PATH)/comWIFI.o \
$(OBJ_PATH)/SSL_TLS.o \
$(OBJ_PATH)/DualSim.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_SIZE_FILE) \
	$(LST_FILE)

	$(OBJ_COPY) -O elf32-littlearm $(INTER_AXF_FILE) $@
	@echo "duplicate bin file :  $@ to $(BINARY_FILE_NO_STRIP)"
	$(CP) $@ $(BINARY_FILE_NO_STRIP)
	@echo "'$@' binary file generated."

#===============================================================================
# Rule for startup files rules generation
#===============================================================================
START_OBJS:= E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/sysroot/usr/lib/crti.o \
E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/sysroot/usr/lib/gcrt1.o \
E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3/crtbegin.o \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/startfiles/startup_tplusentry.o \

END_OBJS:= E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/lib/gcc/arm-islero-linux-gnueabi/4.7.3/crtend.o \
E:/Ingenico/IngeDev_8.18.0.5/toolchains/gnuArm47v7a-4/arm-islero-linux-gnueabi/sysroot/usr/lib/crtn.o \
C:/Program\ Files/TeliumSDK/SDK11.16.7.PatchD/SDKTPLUS/HW_TETRA/gnu_473/startfiles/stapp_legacyexitpoint.o \


#-------------------------------------------------------------------------------
# Rule for includes @option file
#-------------------------------------------------------------------------------
$(INCLUDE_FILE_OPT):  $(DEPENDENCIES) | createObjDir
	@echo "Includes file list @option generation: "
	@$(PRINTF) "\n \"%s\"" $(INCLUDES_PATH) > $@
	@echo "'Finished building: $@'"
	@echo ""
#===============================================================================
# Rule for linker opt files rules generation
#===============================================================================
$(LD_OPT_FILE):  $(DEPENDENCIES) $(SRC_OBJS)  $(LIBS) \
	$(START_OBJS) $(END_OBJS)

	@echo ""
	@echo "Linker file @option generation"
	@$(PRINTF) "\n \"%s\" " $(START_OBJS) $(SYSTEM_LIBS_PATH) > $@
	@$(PRINTF) "\n \"%s\" " $(LIBS_RPATH_LINK) $(SRC_OBJS) >> $@
	@$(PRINTF) "\n \"%s\" " "--start-group"  $(LIBS) $(SYSTEM_LIBS) "--end-group" $(END_OBJS) >> $@
	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(LD_OPT_FILE) \
	$(SRC_OBJS)

	@echo "'$@' link in progress..."
	$(LD) $(LD_OPTS)  -o $@ \
	@$(LD_OPT_FILE)

	@echo "'Finished building: $@'"
	@echo ""

#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_SIZE_FILE): $(INTER_AXF_FILE)
	@echo "'Invoking: GNUARM Print Size'"
	$(SIZE) -A $< > $@
	@echo "'Finished building: $@'"
	@echo ""

#===============================================================================
# Rule for the .lst Generation
#===============================================================================
$(LST_FILE): $(INTER_AXF_FILE)
	$(OBJ_DUMP) $(OD_OPTS) $<  > $@
	@echo "'$@' lst file generated."

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: Src/Main.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Main.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Entry.d
endif
$(OBJ_PATH)/Entry.o: Src/Entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Entry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Entry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/AdviseMgr.d
endif
$(OBJ_PATH)/AdviseMgr.o: Src/AdviseMgr.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/AdviseMgr.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/AdviseMgr.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Backlight.d
endif
$(OBJ_PATH)/Backlight.o: Src/Backlight.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Backlight.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Backlight.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Buzzer.d
endif
$(OBJ_PATH)/Buzzer.o: Src/Buzzer.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Buzzer.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Buzzer.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComEthernet.d
endif
$(OBJ_PATH)/ComEthernet.o: Src/ComEthernet.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComEthernet.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComEthernet.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComGPRS.d
endif
$(OBJ_PATH)/ComGPRS.o: Src/ComGPRS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComGPRS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComGPRS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComModem.d
endif
$(OBJ_PATH)/ComModem.o: Src/ComModem.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComModem.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComModem.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComPPP.d
endif
$(OBJ_PATH)/ComPPP.o: Src/ComPPP.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComPPP.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComPPP.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComSerial.d
endif
$(OBJ_PATH)/ComSerial.o: Src/ComSerial.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComSerial.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComSerial.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComUSB.d
endif
$(OBJ_PATH)/ComUSB.o: Src/ComUSB.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComUSB.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComUSB.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ConfFlash.d
endif
$(OBJ_PATH)/ConfFlash.o: Src/ConfFlash.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ConfFlash.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ConfFlash.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ConfHardware.d
endif
$(OBJ_PATH)/ConfHardware.o: Src/ConfHardware.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ConfHardware.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ConfHardware.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ConfSoftware.d
endif
$(OBJ_PATH)/ConfSoftware.o: Src/ConfSoftware.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ConfSoftware.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ConfSoftware.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/crypto.d
endif
$(OBJ_PATH)/crypto.o: Src/crypto.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/crypto.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/crypto.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Delay.d
endif
$(OBJ_PATH)/Delay.o: Src/Delay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Delay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Delay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/DialogBox.d
endif
$(OBJ_PATH)/DialogBox.o: Src/DialogBox.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/DialogBox.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/DialogBox.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Display.d
endif
$(OBJ_PATH)/Display.o: Src/Display.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Display.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Display.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/DLL.d
endif
$(OBJ_PATH)/DLL.o: Src/DLL.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/DLL.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/DLL.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/dukpt.d
endif
$(OBJ_PATH)/dukpt.o: Src/dukpt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/dukpt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/dukpt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_ActionAnalysis.d
endif
$(OBJ_PATH)/EMV_ActionAnalysis.o: Src/EMV_ActionAnalysis.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_ActionAnalysis.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_ActionAnalysis.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_AppSel.d
endif
$(OBJ_PATH)/EMV_AppSel.o: Src/EMV_AppSel.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_AppSel.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_AppSel.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_CVM.d
endif
$(OBJ_PATH)/EMV_CVM.o: Src/EMV_CVM.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_CVM.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_CVM.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_FinalSelect.d
endif
$(OBJ_PATH)/EMV_FinalSelect.o: Src/EMV_FinalSelect.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_FinalSelect.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_FinalSelect.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_Init.d
endif
$(OBJ_PATH)/EMV_Init.o: Src/EMV_Init.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_Init.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_Init.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_Manager.d
endif
$(OBJ_PATH)/EMV_Manager.o: Src/EMV_Manager.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_Manager.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_Manager.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_OnlineProcessing.d
endif
$(OBJ_PATH)/EMV_OnlineProcessing.o: Src/EMV_OnlineProcessing.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_OnlineProcessing.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_OnlineProcessing.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_ServicesEmv.d
endif
$(OBJ_PATH)/EMV_ServicesEmv.o: Src/EMV_ServicesEmv.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_ServicesEmv.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_ServicesEmv.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_Stop.d
endif
$(OBJ_PATH)/EMV_Stop.o: Src/EMV_Stop.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_Stop.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_Stop.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_Support.d
endif
$(OBJ_PATH)/EMV_Support.o: Src/EMV_Support.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_Support.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_Support.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_UserInterface.d
endif
$(OBJ_PATH)/EMV_UserInterface.o: Src/EMV_UserInterface.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_UserInterface.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_UserInterface.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EMV_UserInterfaceDisplay.d
endif
$(OBJ_PATH)/EMV_UserInterfaceDisplay.o: Src/EMV_UserInterfaceDisplay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EMV_UserInterfaceDisplay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EMV_UserInterfaceDisplay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/English.d
endif
$(OBJ_PATH)/English.o: Src/English.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/English.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/English.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Convert.d
endif
$(OBJ_PATH)/EPSTOOL_Convert.o: Src/EPSTOOL_Convert.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EPSTOOL_Convert.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Convert.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_PinEntry.d
endif
$(OBJ_PATH)/EPSTOOL_PinEntry.o: Src/EPSTOOL_PinEntry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EPSTOOL_PinEntry.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_PinEntry.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_TlvTree.d
endif
$(OBJ_PATH)/EPSTOOL_TlvTree.o: Src/EPSTOOL_TlvTree.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EPSTOOL_TlvTree.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_TlvTree.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/EPSTOOL_Unicode.d
endif
$(OBJ_PATH)/EPSTOOL_Unicode.o: Src/EPSTOOL_Unicode.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/EPSTOOL_Unicode.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/EPSTOOL_Unicode.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/FFMS.d
endif
$(OBJ_PATH)/FFMS.o: Src/FFMS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/FFMS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/FFMS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/FMG.d
endif
$(OBJ_PATH)/FMG.o: Src/FMG.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/FMG.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/FMG.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/FontISO8859.d
endif
$(OBJ_PATH)/FontISO8859.o: Src/FontISO8859.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/FontISO8859.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/FontISO8859.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/FontUTF8.d
endif
$(OBJ_PATH)/FontUTF8.o: Src/FontUTF8.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/FontUTF8.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/FontUTF8.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/globals.d
endif
$(OBJ_PATH)/globals.o: Src/globals.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/globals.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/globals.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Goal.d
endif
$(OBJ_PATH)/Goal.o: Src/Goal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Goal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Goal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Graphic.d
endif
$(OBJ_PATH)/Graphic.o: Src/Graphic.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Graphic.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Graphic.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/IAC.d
endif
$(OBJ_PATH)/IAC.o: Src/IAC.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/IAC.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/IAC.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/IAM.d
endif
$(OBJ_PATH)/IAM.o: Src/IAM.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/IAM.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/IAM.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/iso8583.d
endif
$(OBJ_PATH)/iso8583.o: Src/iso8583.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/iso8583.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/iso8583.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Keyboard.d
endif
$(OBJ_PATH)/Keyboard.o: Src/Keyboard.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Keyboard.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Keyboard.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Layout.d
endif
$(OBJ_PATH)/Layout.o: Src/Layout.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Layout.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Layout.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/LIB.d
endif
$(OBJ_PATH)/LIB.o: Src/LIB.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/LIB.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/LIB.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/log.d
endif
$(OBJ_PATH)/log.o: Src/log.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/log.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/log.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Magnetic.d
endif
$(OBJ_PATH)/Magnetic.o: Src/Magnetic.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Magnetic.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Magnetic.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Mapapp.d
endif
$(OBJ_PATH)/Mapapp.o: Src/Mapapp.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Mapapp.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Mapapp.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/MapTra.d
endif
$(OBJ_PATH)/MapTra.o: Src/MapTra.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/MapTra.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/MapTra.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/MenuManager.d
endif
$(OBJ_PATH)/MenuManager.o: Src/MenuManager.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/MenuManager.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/MenuManager.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/MenuProcessing.d
endif
$(OBJ_PATH)/MenuProcessing.o: Src/MenuProcessing.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/MenuProcessing.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/MenuProcessing.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Message.d
endif
$(OBJ_PATH)/Message.o: Src/Message.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Message.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Message.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/OnlineProcessing.d
endif
$(OBJ_PATH)/OnlineProcessing.o: Src/OnlineProcessing.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/OnlineProcessing.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/OnlineProcessing.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Printer.d
endif
$(OBJ_PATH)/Printer.o: Src/Printer.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Printer.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Printer.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/req.d
endif
$(OBJ_PATH)/req.o: Src/req.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/req.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/req.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rsp.d
endif
$(OBJ_PATH)/rsp.o: Src/rsp.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/rsp.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rsp.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Schemes.d
endif
$(OBJ_PATH)/Schemes.o: Src/Schemes.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Schemes.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Schemes.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/secureISO.d
endif
$(OBJ_PATH)/secureISO.o: Src/secureISO.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/secureISO.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/secureISO.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Smart.d
endif
$(OBJ_PATH)/Smart.o: Src/Smart.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Smart.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Smart.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Sqlite.d
endif
$(OBJ_PATH)/Sqlite.o: Src/Sqlite.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Sqlite.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Sqlite.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TaskAnimation.d
endif
$(OBJ_PATH)/TaskAnimation.o: Src/TaskAnimation.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TaskAnimation.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TaskAnimation.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TaskMutex.d
endif
$(OBJ_PATH)/TaskMutex.o: Src/TaskMutex.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TaskMutex.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TaskMutex.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TaskSemaphore.d
endif
$(OBJ_PATH)/TaskSemaphore.o: Src/TaskSemaphore.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TaskSemaphore.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TaskSemaphore.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Timer.d
endif
$(OBJ_PATH)/Timer.o: Src/Timer.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Timer.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Timer.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Utility.d
endif
$(OBJ_PATH)/Utility.o: Src/Utility.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Utility.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Utility.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/VFS.d
endif
$(OBJ_PATH)/VFS.o: Src/VFS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/VFS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/VFS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/rev.d
endif
$(OBJ_PATH)/rev.o: Src/rev.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/rev.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/rev.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/val.d
endif
$(OBJ_PATH)/val.o: Src/val.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/val.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/val.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/TaskGPRS.d
endif
$(OBJ_PATH)/TaskGPRS.o: Src/TaskGPRS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/TaskGPRS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/TaskGPRS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Batch.d
endif
$(OBJ_PATH)/Cless_Batch.o: Src/Cless_Batch.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Batch.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Batch.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_BlackList.d
endif
$(OBJ_PATH)/Cless_BlackList.o: Src/Cless_BlackList.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_BlackList.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_BlackList.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Common.d
endif
$(OBJ_PATH)/Cless_Common.o: Src/Cless_Common.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Common.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Common.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Customisation.d
endif
$(OBJ_PATH)/Cless_Customisation.o: Src/Cless_Customisation.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Customisation.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Customisation.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_DataExchange.d
endif
$(OBJ_PATH)/Cless_DataExchange.o: Src/Cless_DataExchange.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_DataExchange.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_DataExchange.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Discover.d
endif
$(OBJ_PATH)/Cless_Discover.o: Src/Cless_Discover.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Discover.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Discover.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_DiscoverDPAS.d
endif
$(OBJ_PATH)/Cless_DiscoverDPAS.o: Src/Cless_DiscoverDPAS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_DiscoverDPAS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_DiscoverDPAS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Disk.d
endif
$(OBJ_PATH)/Cless_Disk.o: Src/Cless_Disk.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Disk.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Disk.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_DumpData.d
endif
$(OBJ_PATH)/Cless_DumpData.o: Src/Cless_DumpData.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_DumpData.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_DumpData.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_ExplicitSelection.d
endif
$(OBJ_PATH)/Cless_ExplicitSelection.o: Src/Cless_ExplicitSelection.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_ExplicitSelection.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_ExplicitSelection.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_ExpressPay.d
endif
$(OBJ_PATH)/Cless_ExpressPay.o: Src/Cless_ExpressPay.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_ExpressPay.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_ExpressPay.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Fill.d
endif
$(OBJ_PATH)/Cless_Fill.o: Src/Cless_Fill.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Fill.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Fill.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_GlobalTransactionData.d
endif
$(OBJ_PATH)/Cless_GlobalTransactionData.o: Src/Cless_GlobalTransactionData.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_GlobalTransactionData.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_GlobalTransactionData.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Goal.d
endif
$(OBJ_PATH)/Cless_Goal.o: Src/Cless_Goal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Goal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Goal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_GuiState.d
endif
$(OBJ_PATH)/Cless_GuiState.o: Src/Cless_GuiState.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_GuiState.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_GuiState.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Interac.d
endif
$(OBJ_PATH)/Cless_Interac.o: Src/Cless_Interac.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Interac.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Interac.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Manager.d
endif
$(OBJ_PATH)/Cless_Manager.o: Src/Cless_Manager.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Manager.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Manager.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_NameList.d
endif
$(OBJ_PATH)/Cless_NameList.o: Src/Cless_NameList.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_NameList.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_NameList.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Parameters.d
endif
$(OBJ_PATH)/Cless_Parameters.o: Src/Cless_Parameters.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Parameters.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Parameters.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_PayPass.d
endif
$(OBJ_PATH)/Cless_PayPass.o: Src/Cless_PayPass.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_PayPass.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_PayPass.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_payWave.d
endif
$(OBJ_PATH)/Cless_payWave.o: Src/Cless_payWave.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_payWave.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_payWave.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_PinEnManagement.d
endif
$(OBJ_PATH)/Cless_PinEnManagement.o: Src/Cless_PinEnManagement.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_PinEnManagement.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_PinEnManagement.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_PinEntryGoal.d
endif
$(OBJ_PATH)/Cless_PinEntryGoal.o: Src/Cless_PinEntryGoal.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_PinEntryGoal.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_PinEntryGoal.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_PinManagement.d
endif
$(OBJ_PATH)/Cless_PinManagement.o: Src/Cless_PinManagement.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_PinManagement.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_PinManagement.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Receipt.d
endif
$(OBJ_PATH)/Cless_Receipt.o: Src/Cless_Receipt.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Receipt.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Receipt.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Scan.d
endif
$(OBJ_PATH)/Cless_Scan.o: Src/Cless_Scan.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Scan.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Scan.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Servcomm.d
endif
$(OBJ_PATH)/Cless_Servcomm.o: Src/Cless_Servcomm.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Servcomm.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Servcomm.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Settings.d
endif
$(OBJ_PATH)/Cless_Settings.o: Src/Cless_Settings.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Settings.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Settings.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Term.d
endif
$(OBJ_PATH)/Cless_Term.o: Src/Cless_Term.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Term.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Term.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_Torn.d
endif
$(OBJ_PATH)/Cless_Torn.o: Src/Cless_Torn.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_Torn.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_Torn.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_TransactionFile.d
endif
$(OBJ_PATH)/Cless_TransactionFile.o: Src/Cless_TransactionFile.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_TransactionFile.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_TransactionFile.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_VisaWave.d
endif
$(OBJ_PATH)/Cless_VisaWave.o: Src/Cless_VisaWave.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_VisaWave.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_VisaWave.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_XML.d
endif
$(OBJ_PATH)/Cless_XML.o: Src/Cless_XML.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_XML.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_XML.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/perf_log.d
endif
$(OBJ_PATH)/perf_log.o: Src/perf_log.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/perf_log.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/perf_log.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/UserInterfaceHelpers.d
endif
$(OBJ_PATH)/UserInterfaceHelpers.o: Src/UserInterfaceHelpers.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/UserInterfaceHelpers.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/UserInterfaceHelpers.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/CLESS_lang.d
endif
$(OBJ_PATH)/CLESS_lang.o: Src/CLESS_lang.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/CLESS_lang.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/CLESS_lang.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/fnc.d
endif
$(OBJ_PATH)/fnc.o: Src/fnc.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/fnc.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/fnc.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Cless_QuickPass.d
endif
$(OBJ_PATH)/Cless_QuickPass.o: Src/Cless_QuickPass.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/Cless_QuickPass.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Cless_QuickPass.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/ComSSL.d
endif
$(OBJ_PATH)/ComSSL.o: Src/ComSSL.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/ComSSL.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/ComSSL.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/comWIFI.d
endif
$(OBJ_PATH)/comWIFI.o: Src/comWIFI.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/comWIFI.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/comWIFI.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/SSL_TLS.d
endif
$(OBJ_PATH)/SSL_TLS.o: Src/SSL_TLS.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/SSL_TLS.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/SSL_TLS.o)
	@echo "done!"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/DualSim.d
endif
$(OBJ_PATH)/DualSim.o: Src/DualSim.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES) $(INCLUDE_FILE_OPT)
	@echo "'Src/DualSim.c' compilation in progress..."
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<" @$(INCLUDE_FILE_OPT)
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/DualSim.o)
	@echo "done!"
endif


#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@echo "                                     *-*-*"
	@echo "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---"

#===============================================================================
# Rule for build target progress info display
#===============================================================================
.PHONY: displayBuildInProgress
displayBuildInProgress:
	@echo "Build in progress..."

#===============================================================================
# Rule for output directories creation
#===============================================================================
createObjDir: | $(OBJ_PATH)

$(OBJ_PATH):
	@$(MKDIR) "$(OBJ_PATH)"

createBinDir: | $(BIN_PATH)

$(BIN_PATH):
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo displayBuildInProgress createObjDir createBinDir $(BINARY_FILE)
	@echo "done!"
